USE [master]
GO

/****** Object:  Database [BlogEngine]    Script Date: 8/03/2023 7:06:01 p. m. ******/
CREATE DATABASE [BlogEngine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlogEngine', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlogEngine.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BlogEngine_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BlogEngine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlogEngine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlogEngine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlogEngine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlogEngine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlogEngine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlogEngine] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlogEngine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlogEngine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlogEngine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlogEngine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlogEngine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlogEngine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlogEngine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlogEngine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlogEngine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlogEngine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlogEngine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlogEngine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlogEngine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlogEngine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlogEngine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlogEngine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlogEngine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlogEngine] SET RECOVERY FULL 
GO

ALTER DATABASE [BlogEngine] SET  MULTI_USER 
GO

ALTER DATABASE [BlogEngine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlogEngine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlogEngine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlogEngine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlogEngine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlogEngine] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BlogEngine] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlogEngine] SET  READ_WRITE 
GO


